# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

    #   - name: Build the project
    #     env:
    #       CI: false  # Set CI to false to treat warnings as non-errors
    #     run: npm run build
      - name: Configure Git
        run: |
            git config --global user.name "LoukikNaik"  # Replace with your name
            git config --global user.email "loukiknaik@gmail.com"  # Replace with your email


      - name: Deploy to GitHub Pages  
        run: npm run deploy
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}  # Use the GitHub token for authentication